parameters:
    locale: 'en'
    allowedWords: [PHP, MYSQL, SYMFONY, CAKEPHP]
        
services:
    
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
                
    App\Utils\GenerateTags\GenerateTags:
        autowire: true
        public: true
        arguments:
            $config: {min_word_length: 3, min_word_occurrence: 2, max_words: 8, allowedWords: '%allowedWords%', restrict: false, allowed: true}